import type { ArtistConfig } from './types';

// Migos tracker. Data served from committed CSV snapshots under
// public/migosgold/data/*.csv, transformed from the source Google-Sheet exports by
// scripts/build-bigupdate-csvs.py. An era only appears in the Music grid if its
// name is a key in ALBUM_RELEASE_DATES.
export const migosgoldConfig: ArtistConfig = {
  slug: 'migosgold',
  SITE_NAME: 'MIGOSGOLD',
  SITE_DESCRIPTION: 'The Best Migos Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/migosgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'migosgold_',

  HARDCODED_SHEET_ID: '1MgVRlGs5DL7keB_I6YPEj4FYLOHb8DVJbxN5-h6yxOE',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',

  accentColor: '#ca8a04',
  artistLabel: 'Migos',
  cardLetter: 'M',
  logoUrl: '',
  artistPhotoUrl: '/artists/migosgold.jpg',

  getArtistName() {
    return 'Migos';
  },

  CUSTOM_IMAGES: {
    'No Label II': '/migosgold/eras/no-label-ii.jpg',
    'Yung Rich Nation': '/migosgold/eras/yung-rich-nation.jpg',
    'MigoThuggin': '/migosgold/eras/migothuggin.jpg',
    'YRN 2': '/migosgold/eras/yrn-2.jpg',
    'Culture': '/migosgold/eras/culture.jpg',
    'Culture II': '/migosgold/eras/culture-ii.jpg',
    'Culture III': '/migosgold/eras/culture-iii.jpg',
    'Huncho Jack, Jack Huncho': '/migosgold/eras/huncho-jack-jack-huncho.jpg',
    'QUAVO HUNCHO': '/migosgold/eras/quavo-huncho.jpg',
    'Huncho Records': '/migosgold/eras/huncho-records.jpg',
    'Cheat Code': '/migosgold/eras/cheat-code.jpg',
    'Only Built For Infinity Links': '/migosgold/eras/only-built-for-infinity-links.jpg',
    'Rocket Power': '/migosgold/eras/rocket-power.jpg',
    'QRÖMELIFE': '/migosgold/eras/qr-melife.jpg',
    'Without Warning': '/migosgold/eras/without-warning.jpg',
    'Father Of 4': '/migosgold/eras/father-of-4.jpg',
    'SET IT OFF': '/migosgold/eras/set-it-off.jpg',
    'Collaboration with Gunna': '/migosgold/eras/collaboration-with-gunna.jpg',
    'KIARI': '/migosgold/eras/kiari.png',
    'The Last Rocket': '/migosgold/eras/the-last-rocket.jpg',
    'Collaboration with Rich The Kid': '/migosgold/eras/collaboration-with-rich-the-kid.jpg',
    'Posthumous career': '/migosgold/eras/posthumous-career.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'No Label II': '02/25/2014',
    'Yung Rich Nation': '07/31/2015',
    'MigoThuggin': '??/??/????',
    'YRN 2': '??/??/????',
    'Culture': '01/27/2017',
    'Without Warning': '10/30/2017',
    'Huncho Jack, Jack Huncho': '12/21/2017',
    'Culture II': '01/26/2018',
    'The Last Rocket': '11/02/2018',
    'Father Of 4': '02/22/2019',
    'Father Of 4 (Deluxe)': '02/22/2019',
    'QUAVO HUNCHO': '10/12/2018',
    'Culture III': '06/11/2021',
    'Collaboration with Rich The Kid': '??/??/????',
    'SET IT OFF': '10/13/2023',
    'Collaboration with Gunna': '06/28/2024',
    'KIARI': '08/22/2025',
    'GMFU': '10/23/2026',
    'Unknown': '??/??/????',
    'Huncho Records': '??/??/????',
    'Cheat Code': '??/??/????',
    'Only Built For Infinity Links': '10/07/2022',
    'Posthumous career': '??/??/????',
    'Rocket Power': '08/18/2023',
    'Satchamo': '??/??/????',
    'QRÖMELIFE': '10/02/2026',
    'Post Culture III': '??/??/????',
    'Ongoing': '??/??/????'
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'No Label II': 'No Label 2 is the fourth mixtape by American hip hop group Migos',
    'Yung Rich Nation': 'Yung Rich Nation is the debut studio album by American hip hop group Migos. It was released on July 31, 2015, by Quality Control Music, 300 Entertainment and Atlantic Records.',
    'MigoThuggin': 'Collaboration mixtape between Migos & Young Thug worked in 2015, it was scrapped on December 25, 2015',
    'YRN 2': 'YRN 2 is the seventh mixtape by American hip hop group Migos',
    'Culture': 'The trio first initially announced that the title for their second album would be called No Label 3, however, they later changed it to Culture. After it was scheduled for release in October 2016, the release of the album was delayed due to their conflict with 300 Entertainment.',
    'Huncho Jack, Jack Huncho': 'Collaborative album between Quavo & Travis Scott dropped after many snippet were previewed in 2016 & 2017',
    'Culture II': 'Culture II is the third studio album by American hip hop group Migos. It was released on January 26, 2018, by Quality Control Music, Capitol Records and Motown.',
    'Culture III': 'Culture III is the fourth and final studio album by American hip-hop group Migos. It was released on June 11, 2021, by Quality Control Music and Motown.',
    'SET IT OFF': 'Album was scheduled to drop on November 11 2022, but was delayed due to Takeoff passing',
    'Collaboration with Gunna': 'On December 19, 2023, Gunna and Offset were pictured together in Dubai. 3 months later, "Prada Dem" was released as a single for One of Wun on March 15, 2024. The duo also released the single "Style Rare" on June 28, 2024. Throughout 2024 and 2025, Offset liked and reposted several posts and comments hinting at a collaborative project with Gunna, such as this tweet on February 28, 2025',
    'KIARI': 'KIARI is Offset\'s third solo album, described as his most personal album, Kiari being is real name',
    'Cheat Code': 'Shortly after the release of Culture III, Quavo started previewing multiple snippets. Early 2022, Quavo said that all 3 of the Migos would be releasing solo albums, he confirmed in February 2022 the title of his album to be "Cheat Code". "Cheat Code" never dropped due to his conflict with Offset & led to a duo album with Takeoff',
    'Only Built For Infinity Links': 'Collaborative album between Quavo & Takeoff initiated after a conflict with Offset. Album is composed of newly recorded songs & throwaways from Migos latest album "Culture III"',
    'Rocket Power': '"Rocket Power" was released in tribute of Takeoff, after his tragic death on November 1, 2022',
    'Satchamo': 'On September 22, 2023, Quavo announced a "mixtape vault", suggesting that fans wanted songs would be included in the project. In 2024 the mixtape became an album with the title "Satachamo". On November 8, 2024, Quavo was on Kai Cenat stream and said he wes on the final stage of completing the album, cover art was being shoot & he was doing the songs selections for the tracklist (choosing about 25 songs between 100 songs) On May 2025, Quavo said Satchamo would come out in July 2025. On October 25, 2025, Quavo revealed the feature list of the album, including Yeat, Travis Scott, Pharell Williams, 21 Savage, Young Thug & Lil Yachty',
    'QRÖMELIFE': 'Quavo teased "Away" on September 10 2025, when he 1st worked with Pharell Williams at LV Headquarters in Paris. In October 11, 2025, he announced that his album would be executive produced by Pharell Williams. Satchamo was no longer being worked  on & the focus became to record music with Pharell, wich led to QRÖMELIFE',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},

  ALBUM_ORDER: [
    'No Label II',
    'Yung Rich Nation',
    'MigoThuggin',
    'YRN 2',
    'Culture',
    'Without Warning',
    'Huncho Jack, Jack Huncho',
    'Culture II',
    'The Last Rocket',
    'Father Of 4',
    'Father Of 4 (Deluxe)',
    'QUAVO HUNCHO',
    'Culture III',
    'Collaboration with Rich The Kid',
    'SET IT OFF',
    'Collaboration with Gunna',
    'KIARI',
    'GMFU',
    'Unknown',
    'Huncho Records',
    'Cheat Code',
    'Only Built For Infinity Links',
    'Posthumous career',
    'Rocket Power',
    'Satchamo',
    'QRÖMELIFE',
    'Post Culture III',
    'Ongoing'
  ],

  // the standard tracker key — sheets prefix song names with these emojis
  TAG_MAP: {
    '⭐': 'Best Of', '⭐️': 'Best Of',
    '✨': 'Special',
    '🏆': 'Grails',
    '🥇': 'Wanted', '🏅': 'Wanted',
    '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🤖': 'AI',
  },
  TAG_TOOLTIP_MAP: {
    'Best Of': 'Some of the best leaks hosted on the tracker.',
    'Special': 'Standout songs that are not good enough to belong in Best Of, but still deserve to be highlighted.',
    'Grails': 'The most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as Grails.',
    'Worst Of': 'Some of the worst leaks on the tracker.',
    'AI': 'Involves AI-generated content (e.g. an AI instrumental or AI artist).',
  },
  ERA_THEMES: {},
  hasSubAlbumsTab: false, // no sub-albums data for this tracker
};
