import type { ArtistConfig } from './types';

// NBA YoungBoy tracker. Data served from committed CSV snapshots under
// public/nbayoungboygold/data/*.csv, transformed from the source Google-Sheet exports by
// scripts/build-bigupdate-csvs.py. An era only appears in the Music grid if its
// name is a key in ALBUM_RELEASE_DATES.
export const nbayoungboygoldConfig: ArtistConfig = {
  slug: 'nbayoungboygold',
  SITE_NAME: 'NBAYOUNGBOYGOLD',
  SITE_DESCRIPTION: 'The Best NBA YoungBoy Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/nbayoungboygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'nbayoungboygold_',

  HARDCODED_SHEET_ID: '1-eJxsD-YciRGsQ6367NQ8zKdVJKEq8pirJPcwncgSwg',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',

  accentColor: '#16a34a',
  artistLabel: 'NBA YoungBoy',
  cardLetter: 'Y',
  logoUrl: '',
  artistPhotoUrl: '/artists/nbayoungboygold.jpg',

  getArtistName() {
    return 'NBA YoungBoy';
  },

  CUSTOM_IMAGES: {},

  ALBUM_RELEASE_DATES: {
    'Pre 38 Baby': '??/??/????',
    '38 Baby': '??/??/????',
    'AI YoungBoy [V1]': '??/??/????',
    'AI YoungBoy [V2]': '??/??/????',
    '38 Baby 2 [V1]': '??/??/????',
    'Broken Hearted': '??/??/????',
    'Ain\'t Too Long [V2]': '??/??/????',
    'Too Fast': '??/??/????',
    'The Fault In Me': '??/??/????',
    'Fed Babie\'s': '??/??/????',
    'AHLAN': '??/??/????',
    'From The Bayou [V1]': '??/??/????',
    'Until Death Call My Name [V3]': '??/??/????',
    'Master The Day Of Judgment': '??/??/????',
    '4444': '??/??/????',
    'Decided': '??/??/????',
    'Boosie Collab Tape (2018)': '??/??/????',
    '38 Baby 2 [V3]': '??/??/????',
    'Realer': '??/??/????',
    'AI YoungBoy 2': '??/??/????',
    '(2019) House Arrest': '??/??/????',
    'Still Flexin, Still Steppin': '??/??/????',
    '38 Baby 2 [V5]': '??/??/????',
    'TOP': '??/??/????',
    'Until I Return': '??/??/????',
    'Sincerely, Kentrell [V1]': '??/??/????',
    'Sincerely, Kentrell [V2]': '??/??/????',
    'Colors': '??/??/????',
    'BETTER THAN YOU': '??/??/????',
    'The Last Slimeto': '??/??/????',
    'Realer 2 [V2] - MIGAF': '??/??/????',
    'I Rest My Case': '??/??/????',
    'DTTAH & Richest Opp': '??/??/????',
    '004KT': '??/??/????',
    'Girl': '??/??/????',
    'Decided 2': '??/??/????',
    'I Just Got A Lot On My Shoulders': '??/??/????',
    'MASA': '??/??/????',
    'Slime Cry': '??/??/????'
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Pre 38 Baby': 'Anything unreleased which was recorded before he blew up in the South, in Summer 2016. His Inspirations at the time were rappers such as Lil Phat, Chief Keef, Lil Wayne,  Boosie Badazz, Kevin Gates & Soulja Slim.',
    '38 Baby': 'Youngboy Signs a First record deal to Atlantic Records but was shortly  arrested on attempted murder charges few months later.',
    'AI YoungBoy [V1]': 'Cover was posted by YB in late 2016 before he was arrested but never released due to him later  being arrested. One of the covers has the same picture from the music video "Murda" Which could  have possibly been a single on it.',
    'AI YoungBoy [V2]': 'After being in jail for 6 months, YB received a plea deal and was put on  probation. After he bonded out he instanly got to work and released  untouchable which peaked at 95 on billboard. Ai Youngboy is a more  trap influenced project which differ from his standered lousiana  production.',
    '38 Baby 2 [V1]': 'Announced by YB on Instagram multiple times but never dropped.  Songs in sessions are what songs he recorded / previewed  during this time. "Talkin Shit" & "Coordination" may have been tracks on this tape.',
    'Broken Hearted': 'Announced by YB in the summer of 2017 but never released.  Songs in session was songs that was recorded in the summer of 2017. He worked with ATL Artist Young Thug a lot through this era. He was even gifted a YSL chain and a snake from Young Thug.',
    'Ain\'t Too Long [V2]': 'More agressive rapping than AI YB era and he starts using more  Lousiana production again specfically from Dubba AA.',
    'Too Fast': 'Unreleased collab tape with Lil Uzi Vert. Might not have dropped due to label issues Lil Uzi faced at the time but YB announced it and tweeted the cover art for it.',
    'The Fault In Me': 'Announced by YB in 2018 then didn\'t drop for unkown reasons, later  was announced by his wife Jaz on Twitter in late 2020, then announced again by YB in 2022 and still has yet to drop. Every song  here is speculation.',
    'Fed Babie\'s': 'Dropped a Moneybagg Yo collab tape, after this they fell out  due to YB not being paid for the collab tape.',
    'AHLAN': 'Released and unreleased songs from "Until Death  Call My Name" era could\'ve been originally on this tape. It was confirmed by YB that "Ahlan" was an eight-track solo project from the artist, which includes no features. Production on the tape is handled by Dubba-AA, DMacTooBanging, DJ Swift, Gitt Fai, Louie Bandz and Mike Laury.',
    'From The Bayou [V1]': 'From The Bayou [V1] Originally going to be released but never dropped for unkown reasons. The tracklist was revealed for the project and was supposed to have Steady, We Poppin, Ride, Cap Talk, Everyday & Through The Storm on it.',
    'Until Death Call My Name [V3]': 'Experiment more with melodic melodies, has more high pitched vocals  heavily Influenced by Young Thug. Releases his Debut album "Until Death  Call My Name" After it was pushed back due to him getting arrested and  having controversy over viral video where he is seen slamming his then  girlfriend Jania.',
    'Master The Day Of Judgment': 'Less Higher pitch vocals and autotune compared to "Until Death Call My Name" and previous eras. Songs recorded later in era are mostly themed around the death of YB\'s current manager at the time, Big Dump, who unfortunetly was shot and killed in May 4th, 2018.',
    '4444': 'Heavily Gates influenced flows and improved singing. He starts rapping  more about relgion as he was being taught about Muslim relgion from  Kevin Gates.',
    'Decided': 'Heavy melodic singing through out this era and more darker  heartbreak songs.',
    'Boosie Collab Tape (2018)': 'Boosie confirmed him and YB have a collab tape that is done and was  going to drop but didn\'t due to label issues.',
    'Realer': 'Less high pithced vocals, more deeper melodies, and agressive rapping. Confirmed by files that most songs on "Realer" were recorded November - December 2018.',
    '(2019) House Arrest': 'After getting arrested for violating probation on May 2019 and serving 3  months in jail YB was let out and sentenced to serve house arrest until his  next court case in December 2019 where his probation from 2016 was then  dropped and he was officially a free man. Songs from House Arrest before 10/11/19 were likely throwaways from "AI YoungBoy 2".',
    'Still Flexin, Still Steppin': 'After YB gets off house arrest in December 2019, he links up with Rich The Kid and  through him he meets Jason who later becomes one of his close engineers. He later  announces "Still Flexin, Still Steppin" After doing a poll on twitter deciding wheather  fans wanted a sequal to "Ain\'t Too Long" or Still Flexin, Still Steppin.',
    '38 Baby 2 [V5]': 'This is the 4th and official version of 38 Baby 2 it has heavy autotune  singing with a lot of high pitch vocal inflections, Every song confirmed  recorded on malibu beach by Khris James. Most personal album he has  released to date and one of his personal favoirte albums he released even  calling it his best despite the mixed reviews his fans has/had on the album.',
    'TOP': 'High pitch singing with low tone vocal inflections, more lyrical and  direct Murder songs releases 2nd studio album "TOP".',
    'Until I Return': '"Until I Reurn" a mixtape of heavy autotune singing  with highpitch almost screeching vocals more  Lousiana production.',
    'Sincerely, Kentrell [V1]': 'Originally "Sincerely, Kentrell" was set to release May 7, 2021 but was  pushed back due to yb getting locked up a month before. [V1] was likely  much different than what we got. Songs in session are songs that was  previewed before he got locked up.',
    'Sincerely, Kentrell [V2]': 'Has more sluring/mumbling and singy vocals. (Most likely was on  heavy drugs at the time), era named after viral meme of trolls saying  "YB better ratio" under everyone comments on social media. YB  becomes the 3rd artist in history to go number 1 with an album behind  bars. Fanpages also contributed to the making of the tracklist.',
    'Colors': 'After serving 7 months of jail time YB was let out on bond for a fed case and sentenced to house arrest. YB not only experirmented more with his vocals and singing but he also painted his face going for more of a punk image during this era which caused massive controversy and backlash.',
    'The Last Slimeto': 'A lot of agressive, lyrical flows and melodies, has less singing  compared to previous eras, and a lot more Lousiana Production.  A lot of songs from Realer 2 [V2], 3800 Degreez, MIGAF, 3860, DTTAH &  Richest Opp are speculated to be from this era.',
    'I Rest My Case': 'Experimental vocals, flows, and adlibs some  sounding Young Thug/Yeat/Playboi carti  infleunced. (Was originally planned to have  stopping the violence themed songs on it)',
    'DTTAH & Richest Opp': 'Richest Opp is a mixtape of songs from different eras with more agressive    and slurred vocals on songs that are  from era.',
    '004KT': 'Collab tape with ATL artist Playboi Carti. Has yet  to have any real updates besides es playboi carti  close associates teasing it on twitter with "004KT".',
    'Decided 2': 'Mixtape of songs with more melodic aspects compared to previous releases. Unreleased songs have drugged out vocals with slurred melodies.',
    'I Just Got A Lot On My Shoulders': 'Less coherent vocals compared to Decided 2 era and clearly still on heavy drugs.',
    'MASA': 'After serving 11 months of a 23 month sentence from April 2024 - March 2025 YB was released and placed in to a halfway house for a few weeks. In May 2025, he would then be pardonded by President Trump and announce / plan his "Make America Slime Again" tour for later that year.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},

  ALBUM_ORDER: [
    'Pre 38 Baby',
    '38 Baby',
    'AI YoungBoy [V1]',
    'AI YoungBoy [V2]',
    '38 Baby 2 [V1]',
    'Broken Hearted',
    'Ain\'t Too Long [V2]',
    'Too Fast',
    'The Fault In Me',
    'Fed Babie\'s',
    'AHLAN',
    'From The Bayou [V1]',
    'Until Death Call My Name [V3]',
    'Master The Day Of Judgment',
    '4444',
    'Decided',
    'Boosie Collab Tape (2018)',
    '38 Baby 2 [V3]',
    'Realer',
    'AI YoungBoy 2',
    '(2019) House Arrest',
    'Still Flexin, Still Steppin',
    '38 Baby 2 [V5]',
    'TOP',
    'Until I Return',
    'Sincerely, Kentrell [V1]',
    'Sincerely, Kentrell [V2]',
    'Colors',
    'BETTER THAN YOU',
    'The Last Slimeto',
    'Realer 2 [V2] - MIGAF',
    'I Rest My Case',
    'DTTAH & Richest Opp',
    '004KT',
    'Girl',
    'Decided 2',
    'I Just Got A Lot On My Shoulders',
    'MASA',
    'Slime Cry'
  ],

  // the standard tracker key — sheets prefix song names with these emojis
  TAG_MAP: {
    '⭐': 'Best Of', '⭐️': 'Best Of',
    '✨': 'Special',
    '🏆': 'Grails',
    '🥇': 'Wanted', '🏅': 'Wanted',
    '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🤖': 'AI',
  },
  TAG_TOOLTIP_MAP: {
    'Best Of': 'Some of the best leaks hosted on the tracker.',
    'Special': 'Standout songs that are not good enough to belong in Best Of, but still deserve to be highlighted.',
    'Grails': 'The most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as Grails.',
    'Worst Of': 'Some of the worst leaks on the tracker.',
    'AI': 'Involves AI-generated content (e.g. an AI instrumental or AI artist).',
  },
  ERA_THEMES: {},
  hasSubAlbumsTab: false, // no sub-albums data for this tracker
};
