import type { ArtistConfig } from './types';

// Third Ye tracker variant ("Lol"), built independently from its own Google
// Sheet by scripts/build-yelolgold-csvs.py — NOT copied from yzygold/yegold,
// even though it's a fork of the same catalog and several gids coincide.
// Data served from committed CSV snapshots under public/yelolgold/data/*.csv.
// An era only appears in the Music grid if its name is a key in
// ALBUM_RELEASE_DATES; dates are unknown here since they weren't re-derived
// from this sheet, so every era is a placeholder until filled in by hand.
export const yelolgoldConfig: ArtistConfig = {
  slug: 'yelolgold',
  // Off the landing grid/search — reachable via yegold's alt-tracker picker
  // or directly at /yelolgold/.
  hidden: true,
  hasGroupbuysTab: true,
  hasAlbumCopiesTab: true,
  SITE_NAME: 'YE (Lol)',
  SITE_DESCRIPTION: 'The Kanye West tracker, alternate "Lol" version',
  SITE_URL: 'https://unvaulted.cc/yelolgold/',
  OG_IMAGE_URL: 'https://i.ibb.co/LhXdRh7j/2026-03-23-T184041-712.png',
  STORAGE_PREFIX: 'yelolgold_',

  HARDCODED_SHEET_ID: '1wQ0WC0U9q10fLWpy9CO8YR128eE8msGXqtZI8_cNyTA',
  HARDCODED_SHEET_GID: '199908479',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1wQ0WC0U9q10fLWpy9CO8YR128eE8msGXqtZI8_cNyTA/export?format=csv&gid=689133373',

  alternateTrackers: [
    { slug: 'yegold', label: 'Official' },
    { slug: 'yzygold', label: 'Suzy' },
  ],

  accentColor: '#C9A224',
  artistLabel: 'Ye (Lol)',
  cardLetter: 'LOL',
  logoUrl: '/logos/yzygold.png',
  artistPhotoUrl: '/artists/kanye.jpg',
  navLogoUrl: '/yzygold/logo.png',

  getArtistName() {
    return 'Kanye West';
  },

  // Ported from yegold (.net, preferred) and yzygold (Suzy, fallback for the
  // two eras yegold no longer tracks under these exact names — see the note
  // above ALBUM_RELEASE_DATES). Not every yelolgold era maps 1:1 to yegold's
  // post-audit names (e.g. yelolgold's sheet still uses "Bad Bitch Playbook"
  // rather than "¥$", confirmed against its own live data), so these are
  // keyed to match yelolgold's own ALBUM_RELEASE_DATES, not yegold's.
  CUSTOM_IMAGES: {
    "Before The College Dropout": "https://i.ibb.co/kpk9TzL/image-2026-05-04-074305465.png",
    "The College Dropout": "https://i.ibb.co/mrK8W4rL/image-2026-03-22-142639537.png",
    "Late Registration": "https://i.ibb.co/QvNMHS7f/image-2026-05-04-074325717.png",
    "Graduation": "https://i.ibb.co/gZmLyhpD/image-2026-05-04-074348808.png",
    "808s & Heartbreak": "https://i.ibb.co/gL1jHjxD/image-2026-05-04-074412180.png",
    "Good Ass Job": "https://i.ibb.co/zWDJvnF3/image-2026-05-04-074429956.png",
    "My Beautiful Dark Twisted Fantasy": "https://i.ibb.co/nMhS9cfq/image-2026-05-04-074450433.png",
    "Watch The Throne": "https://i.ibb.co/Gvh0rdt/ea89bace-a565-4fd7-aec2-de7f2a0341a2.jpg",
    "Cruel Summer": "https://i.ibb.co/wr7sS6DH/cell-Image-199908479-8.png",
    "Thank God For Drugs": "https://i.ibb.co/G32JPb2w/image-2026-05-04-074528355.png", // yzygold (yegold now folds this into Yeezus's alt-name)
    "Yeezus": "https://i.ibb.co/54tTPvy/YEEZUS-COVER-1-scaled.jpg",
    "Cruel Winter [V1]": "/yzygold/CruelWinterV1.jpeg",
    "Yeezus 2": "https://i.ibb.co/gL2VPWGD/image-2026-05-04-074633664.png",
    "So Help Me God": "https://i.ibb.co/Lz3b2xDD/cell-Image-199908479-13.png",
    "SWISH": "https://i.ibb.co/vvdd31rM/image-2026-05-04-074736182.png",
    "The Life Of Pablo": "https://i.ibb.co/n8DkztcP/image-2026-03-22-142914834.png",
    "Cruel Winter [V2]": "https://i.ibb.co/bjFdyLjv/image-2026-04-28-131805413.png",
    "Turbo Grafix 16": "https://i.ibb.co/q3fggHMz/image-2026-03-22-143044324.png",
    "LOVE EVERYONE": "https://i.ibb.co/Tq7HkRKn/cell-Image-199908479-18.png",
    "DAYTONA": "https://i.ibb.co/1fX0N137/Daytona.jpg",
    "ye": "https://i.ibb.co/4ffBbzd/0a170099-f725-41f6-88a9-c28ab2a6bdb8.jpg",
    "KIDS SEE GHOSTS": "https://i.ibb.co/xsRLz4k/28ef3e62-abba-4064-9dd7-44dd37803981.jpg",
    "Good Ass Job (2018)": "https://i.ibb.co/Y4tB29pw/image-2026-05-04-075000044.png",
    "Yandhi [V1]": "https://yetracker.cc/img/9382ca79345e3a764d6f08ac9bc86898",
    "Yandhi [V2]": "https://yetracker.cc/img/ac5edf6afc2f81a5613a5292f137e548",
    "JESUS IS KING": "https://i.ibb.co/6cPT40L6/image-2026-05-04-075046079.png",
    "God's Country": "https://yetracker.cc/img/b05c530912bbca7eab6931b3fe87493e",
    "JESUS IS KING: The Dr. Dre Version": "https://yetracker.cc/img/b10a2746d60af89082ee3fe20fd60a36",
    "DONDA [V1]": "https://i.ibb.co/8rV5JJ3/children-park-manip-retouched.jpg",
    "Donda [V2]": "https://i.ibb.co/JjzVyMvT/image-2026-05-04-075158690.png",
    "Donda [V3]": "https://i.ibb.co/YX9xy2p/19e339a4-33e0-46ec-bd90-0e4ed62932cc.jpg",
    "Jesus Is Born": "/yegold/JesusIsBorn.jpg",
    "Sunday Service Choir": "https://i.ibb.co/nN2LDSxN/SSC.jpg",
    "DONDA 2 [V1]": "https://i.ibb.co/27D2fTXM/image-2026-05-04-075245507.png",
    "WAR": "https://i.ibb.co/93mVjHZV/WAR-youtube-thumbnail.png",
    "YEBU": "https://i.ibb.co/vxTD8nVh/image-2026-05-04-075337930.png",
    "Bad Bitch Playbook": "https://i.ibb.co/jknzBvyZ/image.png", // yzygold (yegold renamed this era to "¥$")
    "VULTURES 1": "https://i.ibb.co/5hFN28jM/cell-Image-199908479-37.png",
    "VULTURES 2": "https://i.ibb.co/35h4bhzG/image-2026-05-04-075431548.png",
    "VULTURES 3": "https://yetracker.cc/img/9c928643e77b50cd0f0e71ea740e6a53",
    "BULLY [V1]": "https://a5.mzstatic.com/us/r1000/0/Music221/v4/4b/38/d1/4b38d146-381d-ace2-73df-24074576e62b/656465138828_cover.jpg",
    "CUCK": "https://yetracker.cc/img/f67f57cf09620b30726b0b7df91a65b8",
    "DONDA 2 [V2]": "https://i.ibb.co/b5ZNpDXk/cover.jpg",
    "IN A PERFECT WORLD": "https://i.ibb.co/Fqd2crvz/iapwcover.png",
    "BULLY [V2]": "https://i.ibb.co/pBfL20KJ/HLNl-Xx-Ubs-AAaz-S8.jpg",
    "Ongoing": "https://i.ibb.co/dwZ4cwmd/image-2026-04-27-185921217.png",
  },

  ALBUM_RELEASE_DATES: {
    'Before The College Dropout': '??/??/????',
    'The College Dropout': '??/??/????',
    'Late Registration': '??/??/????',
    'Graduation': '??/??/????',
    '808s & Heartbreak': '??/??/????',
    'Good Ass Job': '??/??/????',
    'My Beautiful Dark Twisted Fantasy': '??/??/????',
    'Watch The Throne': '??/??/????',
    'Cruel Summer': '??/??/????',
    'Thank God For Drugs': '??/??/????',
    'Yeezus': '??/??/????',
    'Cruel Winter [V1]': '??/??/????',
    'Yeezus 2': '??/??/????',
    'So Help Me God': '??/??/????',
    'SWISH': '??/??/????',
    'The Life Of Pablo': '??/??/????',
    'Cruel Winter [V2]': '??/??/????',
    'Turbo Grafix 16': '??/??/????',
    'LOVE EVERYONE': '??/??/????',
    'DAYTONA': '??/??/????',
    'ye': '??/??/????',
    'KIDS SEE GHOSTS': '??/??/????',
    'Good Ass Job (2018)': '??/??/????',
    'Yandhi [V1]': '??/??/????',
    'Yandhi [V2]': '??/??/????',
    'JESUS IS KING': '??/??/????',
    'God\'s Country': '??/??/????',
    'JESUS IS KING: The Dr. Dre Version': '??/??/????',
    'DONDA [V1]': '??/??/????',
    'Donda [V2]': '??/??/????',
    'Donda [V3]': '??/??/????',
    'Jesus Is Born': '??/??/????',
    'Sunday Service Choir': '??/??/????',
    'DONDA 2 [V1]': '??/??/????',
    'WAR': '??/??/????',
    'YEBU': '??/??/????',
    'Bad Bitch Playbook': '??/??/????',
    'VULTURES 1': '??/??/????',
    'VULTURES 2': '??/??/????',
    'VULTURES 3': '??/??/????',
    'BULLY [V1]': '??/??/????',
    'CUCK': '??/??/????',
    'DONDA 2 [V2]': '??/??/????',
    'IN A PERFECT WORLD': '??/??/????',
    'BULLY [V2]': '??/??/????',
    'Ongoing': '??/??/????'
  },

  // Jesus Is Born is the Sunday Service Choir's own standalone album (merged
  // in from the sheet's SSC tab, see EXTRA_UNRELEASED_GIDS in _sheets.ts) —
  // other SSC recordings are filed under whichever studio era they're from
  // instead, tagged "(Sunday Service Choir)" in the song name.
  HIDDEN_ALBUMS: ['Jesus Is Born', 'Sunday Service Choir'],
  // Sourced directly from each era's own stat-header description cell on this
  // sheet (not ported from yzygold/yegold) — every era in ALBUM_RELEASE_DATES
  // has one here, unlike yegold where 4 eras have no such cell at all.
  ALBUM_DESCRIPTIONS: {
    "Before The College Dropout": "Before Ye released his first album to critical acclaim in 2004, he pursued many other projects, including a rap trio group named the \"Go Getters\" and production for other rappers, including, but not limited to , Common, Talib Kweli, and Scarface. Two years before the release of The College Dropout, Ye began releasing a series of mixtapes to generate hype and publicity for the eventual release of his first album. Ye eventually signed with Roc-A-Fella records in August 2002.",
    "The College Dropout": "Following his signing to Roc-A-Fella Records, Ye released his debut studio album, The College Dropout. It features string arrangements, choirs, and his signature soul sampling, frequently branded as \"chipmunk soul\" for its sped-up and high-pitched nature. Contrary to the popular gangster-persona lyrics at the time, his songs mostly revolved around themes of family, materialism, religion, and racism. The inspiration for finally making his music came when he was in a near-fatal car crash.",
    "Late Registration": "Late Registration continues the social themes introduced in The College Dropout, but now with orchestral production influenced by co-producer Jon Brion. Ye's newfound success allowed him to expand his ambitions from a single violinist to an entire string orchestra, mixing it with production including chipmunk soul and lullaby-like instrumentals. Lyrically, the album features a mix of more socially charged songs to more personal cuts. Production-wise, inspiration came from artists such as British trip-hop band Portishead and Fiona Apple's second album When The Pawn…",
    "Graduation": "Graduation is the third studio album from Ye. Inspiration came from stadium tours, indie rock, and house music. It was a considerable departure from the sound Ye had used on his first two studio albums, which featured samples and inspirations from the soul and orchestral music Ye grew up alongside. This album included a much more electronic sound, featuring layering synthesizers. Lyrically, Ye analyzes himself and talks about his life after becoming famous and how the media criticize him.",
    "808s & Heartbreak": "Following the death of his mother due to complications after cosmetic surgery, his relationship with fiancé Alexis Phifer finally ending for good, and a struggle to adapt to his celebrity status, Ye felt emotionally drained and lost. Ye dealt with his pain by channeling it into a sonically stripped-down album, one dominated by his use of the titular Roland TR-808 drum machine and Auto-Tune. This album significantly influenced future hip-hop music, having influenced Drake, Future, Travis Scott, and more.",
    "Good Ass Job": "As far back as 2003, Ye had planned a four-album series revolving around going to college, with Good Ass Job concluding the series. The death of his mother derailed this plan, with his fourth album becoming the somber 808s & Heartbreak. People still expected Good Ass Job to release, though, as Ye's next album as late as early 2010. When the wake of the 2009 VMAs incident happened, it would cause Good Ass Job not to release. The title seems to have changed to MBDTF around 2009 New Year's Eve or atleast not called GAJ anymore. The cover included for this era is the original cover for the single \"POWER.\"",
    "My Beautiful Dark Twisted Fantasy": "Conceived during West's self-imposed exile following the 2009 VMA incident and further influenced by his deteriorating relationship with model Amber Rose, My Beautiful Dark Twisted Fantasy is a genre-bending masterpiece that explores the darker sides of celebrity, fame, and love. With grand production that sounds like the natural evolution of all the albums that came before it, this is seen by many as Ye's best album, even earning an extremely rare 10/10 rating from Pitchfork. The recording process was finished by October 2010, according to Ye in a tweet. Most tracks were made in Avex in Honolulu, Hawaii, where Ye flew out artists and producers to work on the album. Said sessions also had \"Commandments\", that prohibited Tweeting, taking pictures, and wearing hipster hats.",
    "Watch The Throne": "Considered one of the most legendary collab albums of all time, Watch The Throne puts together two of the most legendary figures in music history for a full studio album. Ye teams up with his big brother, JAŸ-Z, for an album, focused primarily on luxury, black excellence, and the American dream. The album's production also reflects that, and having been recorded by two future billionaires primarily in New York City's Tribeca Grand Hotel, how could it not?",
    "Cruel Summer": "A compilation of new songs from Ye's label, G.O.O.D. Music, 2012's Cruel Summer is one of the most collaborative Ye projects he accomplished. Featuring various collaborations with Pusha T, Big Sean, 2 Chainz, John Legend, and many more, this album spawned many big hits, including \"Mercy\" and the remix of the Chief Keef song \"Don't Like.\" This album also marks the first time Ye would work with Travis Scott, an at-the-time complete unknown with no mixtape to his name.",
    "Thank God For Drugs": "Before Ye chose the name Yeezus for his sixth solo album, the name was Thank God For Drugs. Recording started in 2012 and accelerated in early 2013, with Ye and his producers producing material very quickly. The tracklist for the album boasted 20 songs, with around 3.5 hours of rough material created for the album. After changing the album's name to Yeezus, Ye recruited Rick Rubin to cut down this material and take the music in a minimal direction.",
    "Yeezus": "Yeezus marked a complete reverse from the bombastic production that Ye accomplished on My Beautiful Dark Twisted Fantasy. He swapped lush soul and anthemic hooks for splintering electro, acid house, and industrial force while packaging some of his most lewd and heart-crushing tales. Initially envisioned as Thank God For Drugs, a much larger project, Ye would play the album for Rick Rubin, he later recalled listening to roughly 3-hours of unfinished material that seemed to need months worth of work - despite the release date being a month away. Ye enlisted Rubin to refine and complete the project, finishing a majority of the songs just two days before release.",
    "Cruel Winter [V1]": "The 2013 version of Cruel Winter, the first version of the sequel to 2012's Cruel Summer, is a mystery. No single for this album was released, and most of the info comes from leakers and insiders. It had many songs with A Tribe Called Quest member Q-Tip, who was notably absent from Cruel Summer despite having already been signed to the label. There is no official cover for this album, so we're using a fanmade cover to represent this era.",
    "Yeezus 2": "After Rick Rubin and Ye cut down Yeezus to the final ten tracks, Ye still saw potential in much of the cut material. Thus, shortly after Yeezus was released, an EP of leftovers titled Lost Yeezus was already being teased. The project then evolved into a full-fledged album of mostly new material, with Yeezus 2 acting as a codename before they could choose the last name. This project would develop into So Help Me God as the songs evolved.",
    "So Help Me God": "Announced in February 2015, So Help Me God is now one of Ye's most infamous unreleased projects. Essentially being a more advanced version of the songs developed during the Yeezus 2 era, So Help Me God gained significant hype as the teaser tracks of \"Wolves,\" \"All Day,\" and \"Only One\" was revealed to the public. Despite intending to release the album in March 2015, Ye never finished So Help Me God, and only a few songs from the era ended up on The Life Of Pablo.",
    "SWISH": "After changing the name of his 7th solo album from So Help Me God to SWISH, Ye began to develop all new songs throughout mid-late 2015 meant for the album, with most of them eventually making it onto the final release of The Life Of Pablo. Ye also continued to work on many So Help Me God and Yeezus 2 tracks, but by the end of 2015 and the start of 2016, Ye had dropped most of these tracks from the tracklist for SWISH, which began to resemble the final TLOP tracklist strongly.",
    "The Life Of Pablo": "The Life Of Pablo is Ye's 7th studio album, with constant name changes before release. Sporadic and scatter-shot, the album is one of a kind. The title refers to three people: artist Pablo Picasso, drug dealer Pablo Escobar, and Paul the Apostle, whose name is Pablo in Spanish. The album was initially released only on TIDAL, but later made its way to other streaming services with some updates. Ye finally finished it by adding the track \"Saint Pablo.\"",
    "Cruel Winter [V2]": "After the 2013 rendition of Cruel Winter ended production, Ye revived it in 2016. With only one official single released, this album took many ideas from popular music at the time, including many trap elements, remixes, and the biggest music stars. The label supposedly worked on it as late as November 2017, but the album has yet to come. There isn't an official cover for this album we know of, so we are using the single art for \"Champions.\"",
    "Turbo Grafix 16": "Immediately after Ye released The Life of Pablo, he announced a whole new album titled Turbo Grafx 16, intended to be released in the summer of 2016. Ye intended to pursue a futuristic sound, wanting to incorporate video game samples into the record. However, work on the album was short-lived, as Ye began touring in August 2016 and scrapped the concept entirely after being diagnosed as bipolar. The cover included for this era is unofficial, despite being popular among Ye fans.",
    "LOVE EVERYONE": "After Ye was released from UCLA Medical Hospital and diagnosed as bipolar, he bought a ranch in Wyoming where he would produce his next album and multiple albums for his collaborators. The concept of the album came together in 2018. The album's subject matter varied wildly, with some songs being about introspection and change and others discussing his political views. The public name given for this album is LOVE EVERYONE, but it is known that Ye likely considered the Hitler title longer.",
    "DAYTONA": "In Wyoming, Ye would executive produce Pusha T's album, DAYTONA, his third studio album. It was released on May 25th, 2018, by G.O.O.D. Music and Def Jam Recordings. DAYTONA was announced by Ye via Twitter on April 19th, 2018, alongside the album's release date.",
    "ye": "ye discusses topics in Ye's life, including mental health, family, and addiction. He also explicitly announced his diagnosis of bipolar disorder through the album's artwork and a proclamation within the album. The seven-song project, created in Jackson Hole, Wyoming, was released alongside five other projects. Ye revealed in an interview that after his infamous TMZ interview (in which he stated that slavery was a choice), he completely re-did his album with an entirely new theme.",
    "KIDS SEE GHOSTS": "Out of the five Wyoming projects from 2018, people consider KIDS SEE GHOSTS one of the best. This album focuses heavily on overcoming struggles caused by mental health, which Ye and Cudi have been fighting. It's characterized by many psychedelic and rock-influenced elements, making for an album that sounds like nothing else. This album was officially released on June 8th, 2018, making it Ye's second collab album.",
    "Good Ass Job (2018)": "Ye and Chance collab project that people talked about for years before being officially announced in 2018. The project was supposed to be just seven tracks long, similar to all the Wyoming albums. The central theme of this project is a celebration, as many of the tracks we've heard from this project seem to be very joyful and uplifting. Ye and Chance presumably canceled it sometime in 2019. This project has no covers we know of, so we have used unofficial artwork.",
    "Yandhi [V1]": "Upon hearing the beat to \"Hurricane\" during sessions for Good Ass Job (2018), Ye became inspired to create a whole new album titled Yandhi. With the album's concept in his mind, Ye and his producers began frenzied work as they developed multiple new songs throughout September 2018, aiming for a September 29 release date. As they did not meet this deadline, Ye went to Uganda to conduct further work on the album, but delayed it indefinitely on November 13.",
    "Yandhi [V2]": "After Ye delayed Yandhi indefinitely, he began working with record producer Timbaland to create \"more healing music\" for the album. Shortly after the announcement of the delay, Ye underwent a sudden and dramatic conversion towards born-again evangelical Christianity, debuting the Sunday Service Choir at the start of 2019. The creation of the choir coincided with the songs on Yandhi taking a new Christian lyrical focus. Eventually, the album would morph into the thoroughly Christian JESUS IS KING by mid-2019.",
    "JESUS IS KING": "Following a revelation on Easter 2019 at Coachella, Ye scrapped Yandhi and reworked it to focus on God and Christianity. This album ended up being JESUS IS KING. After a private listening party in Detroit, Kim Kardashian announced that the album would release on Sunday, September 29, following listening parties in Chicago and New York. It didn't, and there were no updates for almost a month. On October 20, 2019, Ye suddenly reappeared on Twitter to announce the final release date.",
    "God's Country": "Shortly after the release of JESUS IS KING, Ye (almost immediately) started working on new material. Songs from this era revolve around his faith while also consisting of dark themes (such as prison) and lyrics about current social issues. Initially announced as God's Country on May 20th, 2020 by Arthur Jafa, tracks from this album would go on to be developed further in the DONDA [V1] era, following Ye getting new inspiration to make an album dedicated to his mother.",
    "JESUS IS KING: The Dr. Dre Version": "The release of JESUS IS KING was met with mixed reviews from fans and critics. Ye then took to Twitter to announce that he was working on a new album with Dr. Dre. Initially conceived as a remix album, it eventually grew to incorporate mainly unreleased material. During the #WESTDAYEVER campaign, Ye did on Twitter in 2020, it was supposed to release officially, but never did. It ended up being scrapped sometime in 2020, as stated by producer Dem Jointz. Ye posted the cover in 2022, which is assumed to be for the album.",
    "DONDA [V1]": "With new inspiration to work on an album dedicated to his mother, Ye continued working on previous demos and new ideas. The music of this era reflects Donda's impact on Ye in a colorful sound while reflecting his mania and the stress he was going through focusing on his businesses while also running for President. With multiple failed release dates for the album, Ye went into silence in early 2021, finishing up tracks until the album morphed into something very different.",
    "Donda [V2]": "After taking a break from music in early 2021, Ye went to work at the Pio Pico studio in LA with an entirely new vision for the album. While the name remained the same, the sound shifted to be more experimental and less soulful. Working with producers such as E.VAX, Dem Jointz, and Digital Nas, Ye went through hundreds of beats, laying down vocals and trying to come up with ideas for songs. This era would continue until Ye decided to finalize the album, shifting to the more minimalistic release sound.",
    "Donda [V3]": "Almost a year after the initial announcement of Donda, a Beats by Dre ad revealed that a listening party would take place at the Mercedes-Benz Stadium in Atlanta. It happened, but the album didn't drop. Ye moved into the stadium and lived there until the second listening event two weeks later. Once again, the album did not release. Ye later announced a third listening party at Soldier Field in Chicago, with the album coming the next day. It didn't. The album ended up releasing on August 29th, 2021 at 8AM EST, almost two days after the final listening party.",
    "Jesus Is Born": "First announced on Ye's interview with Zane Lowe on Apple's Beats 1 Radio station, Jesus Is Born is the first - and only - album from the Sunday Service Choir (also referred to as Sunday Service), a gospel choir founded and led by Ye. It would release on Christmas Day 2019, peaking at #2 on the Billboard U.S. Gospel charts, and #73 on the Billboard 200 charts. The album does not have a single original song, as all are interpolations of other artists' songs - or interpolations of Ye originals.",
    "Sunday Service Choir": "Sunday Service Choir rehearsals and performances with no identifiable source era — everything else recorded at Sunday Service is instead filed under whichever studio era it actually belongs to (e.g. Yandhi, God's Country, DONDA [V1]), tagged \"(Sunday Service Choir)\" in its name.",
    "DONDA 2 [V1]": "Donda 2 was announced by Ye via Instagram, being executive produced by Future. Ye then proceeded to get into many significant controversies. He hosted a listening party for it in Miami, in which many of the tracks were unfinished. It was released on the Stem Player a few days later, but it was still incomplete. Months later, Ye got into even more controversies, making him get dropped by Adidas, buy the social media Parler, and lose his billionaire status following his proclaiming \"White Lives Matter\" at Yeezy Season 9.",
    "WAR": "WAR was a collaborative project between Ye and James Blake. Early sessions for the project began around April/May 2022. On his third Drink Champs interview, Ye referred to these sessions as work for \"their album\". Three songs from the project were played at a party featured on Naomi Campbell's Instagram, with the song \"What I Would Have Said At Virgil's Funeral\" being previewed in full at YZY Season 9 shortly thereafter. The project was thought to have been scrapped in the wake of Ye's numerous antisemitic comments, however James Blake has gone on record to say that Ye is the only thing stopping the project from seeing a release. Was thought to have also been a collaboration with No I.D., but James Blake confirmed he only did production on one session.",
    "YEBU": "Days before Ye was set to hold YZY Season 9, he suddenly changed plans for the event and wore a \"White Lives Matter\" shirt. After that, Ye tweeted about going \"death con 3\" on Jewish people. Following an interview with Alex Jones in which he proclaimed himself a Nazi and claimed he \"liked Hitler,\" many fans and artists gave up supporting Ye and his antics. Following this and an \"apology\" posted on Instagram, Ye went silent for months and began working on new material in Italy with his frequent collaborators. Reportedly being made at the same time as VULTURES. The cover for this era is from the \"Someday We'll All Be Free\" single, as there is currently no artwork available and this cover is widely synonymous with the era.",
    "Bad Bitch Playbook": "Ye and Ty Dolla $ign frequently collaborated during the sessions for YEBU, hinting at a joint project. A snippet featuring Ty was released on October 2, 2023, leading to the song \"BACK TO ME,\" and confirming a joint album via Instagram. TMZ later reported that Ye was producing both a solo album and a collaborative one with Ty. Then, during the Saudi Arabia recording sessions for Bad Bitch Playbook Vol. 1 in November 2023, the name for the collaborative project between Ty Dolla $ign & Ye would be changed to Vultures, with that coming a sonic change in the project.",
    "VULTURES 1": "After the album's name change from Bad Bitch Playbook Vol. 1 to VULTURES 1, four listening parties were scheduled between December 12th, 2023, and February 9th, 2024. In 2024, Ye announced that VULTURES would be a trilogy, with the first installment dropping on February 9th, followed by the second and third albums in March and April. VULTURES 1 would end up being released on February 10th, the day after the final listening party.",
    "VULTURES 2": "VULTURES 2 was announced alongside 2 other volumes of VULTURES, and was meant to release on March 8th, 2024, and then May 3rd, 2024. This album would've became the first release exclusive to the YZYAPP. The cover shows Ty Dolla $ign holding a portrait of his brother Big TC, who is currently in prison. After the album failed to drop on May 3rd, 2024, the direction of the project completely shifted, and was to be censored. The album failed to drop August 2nd and then dropped August 3rd with questionable mixing/songs.",
    "VULTURES 3": "Was announced alongside the 2 other volumes and was set to release on April 5th, 2024, however this didn't happen. The project was thought to have been scrapped after the rushed release of VULTURES 2, and Ye's apparent focus on his solo project BULLY. However, Ty stating that \"V3 boutta rip heads off\" in an 88-Keys IG live chat, and Ye heart reacting a fan's message asking if the project still exists, seem to contridict this. The project was set to drop in 2025, however given Ye's recent statements against Ty Dolla $ign, and his signal on twitter that he was working to remove Ty from Melrose, it's assumed that the project is now scrapped. When asked if the album is coming, Ty Dolla $ign responded with \"Six Seven.\"",
    "BULLY [V1]": "On September 3rd, 2024, the CEO of Channel Candy, Ye's new touring company, confirmed that work on a new solo Ye album had began after the South Korea Vultures listening experience. On September 28th, 2024, on the second Haikou listening event, Ye confirmed that the album name is Bully, which references the movie with the same name that he posted on his Instagram story a few days prior to the event. On January 2nd, 2025, Ye announced the album would have AI on it after months of speculation, and that it could help AI become used more in music. After the release of Bully V1, Ye confirms his intention to re-record the AI on Bully, and stated it was being mixed.",
    "CUCK": "On March 6th, 2025, Ye tweeted, \"this next album got that antisemitic sound\" and \"my new sound called antisemitic\". This would mark a shift in Ye's soundscape, as his antisemitic ideas had been mostly contained to his Twitter at that time, besides a few one-off remarks about Jews on the VULTURES albums. On March 16th, 2025, Ye would tweet an image of a red swastika against a black background, declaring it as a \"NEW ALBUM COVER\". On April 2nd. 2025, DJ Akademiks would post a series of Tweets that eventually led to the announcement of a new album titled WW3, separating this project from BULLY.",
    "DONDA 2 [V2]": "After releasing Donda 2 via the Stem Player in 2022, Ye would eventually move onto other projects. However, the project never left his mind, with some songs continuing to be considered in the Vultures era. 2025 would see Ye enter a new era of creative fuel, once again working on multiple projects at once. With plans to release BULLY and CUCK, Ye also spoke of plans to \"officially\" release Donda 2, repeatedly saying he planned to rerecord verses and upload a \"finished\" version of the album.",
    "IN A PERFECT WORLD": "Announced as IN A PERFECT WORLD, This was labeled as a \"Clean\" Version of Ye's album CUCK, with attempting and testing new production. obviously this concept perished with just few tracks even developed and no further tracks finished than BULLETPROOF. Also has gotten polemic production with the use of Suno AI to write reference tracks and then re-AI. Really a mess of an album.",
    "BULLY [V2]": "After 2 years of controversy, Ye makes his comeback with the goal of removing AI from his album BULLY. He sets his goals and gets back in the studio with the help of Nine Vicious, CeeLo Green, Travis Scott, and presumably many others. After the album gets delayed 2 more times and misses the final release date by a day, Ye releases the album on March 28th, 2026 and begins updating it with new mixing and vocals.",
    "Ongoing": "Beginning the year with mounds of controversy Ye sets on his mind towards a more controversial line of music. He begins on his work for CUCK and brings back the idea of Donda 2 and announces a new album with a \"more antisemetic sound\". After a year Ye would attempt to regain the publics trust, reuniting with Travis Scott and possibly other artists in late 2025 he starts working on rebranding BULLY to have no AI and possibly work on more than BULLY.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},

  ALBUM_ORDER: [
    'Before The College Dropout',
    'The College Dropout',
    'Late Registration',
    'Graduation',
    '808s & Heartbreak',
    'Good Ass Job',
    'My Beautiful Dark Twisted Fantasy',
    'Watch The Throne',
    'Cruel Summer',
    'Thank God For Drugs',
    'Yeezus',
    'Cruel Winter [V1]',
    'Yeezus 2',
    'So Help Me God',
    'SWISH',
    'The Life Of Pablo',
    'Cruel Winter [V2]',
    'Turbo Grafix 16',
    'LOVE EVERYONE',
    'DAYTONA',
    'ye',
    'KIDS SEE GHOSTS',
    'Good Ass Job (2018)',
    'Yandhi [V1]',
    'Yandhi [V2]',
    'JESUS IS KING',
    'God\'s Country',
    'JESUS IS KING: The Dr. Dre Version',
    'DONDA [V1]',
    'Donda [V2]',
    'Donda [V3]',
    'Jesus Is Born',
    'Sunday Service Choir',
    'DONDA 2 [V1]',
    'WAR',
    'YEBU',
    'Bad Bitch Playbook',
    'VULTURES 1',
    'VULTURES 2',
    'VULTURES 3',
    'BULLY [V1]',
    'CUCK',
    'DONDA 2 [V2]',
    'IN A PERFECT WORLD',
    'BULLY [V2]',
    'Ongoing'
  ],

  TAG_MAP: {
    '⭐': 'Best Of',
    '🏆': 'Grails',
    '🥇': 'Wanted',
    '🏅': 'Wanted',
    '✨': 'Special',
    '🗑️': 'Worst Of',
    '🗑': 'Worst Of',
    '🚮': 'Unwanted',
    '🤖': 'AI',
    '⁉️': 'Lost Media',
    '⁉': 'Lost Media',
    '❓': 'Unknown',
  },
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs that are not good enough to be in Best Of, but still deserves to be highlighted.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
  },
  ERA_THEMES: {},
  hasSubAlbumsTab: false,
};
