import type { ArtistConfig } from './types';

// Third Ye tracker variant ("Lol"), built independently from its own Google
// Sheet by scripts/build-yelolgold-csvs.py — NOT copied from yzygold/yegold,
// even though it's a fork of the same catalog and several gids coincide.
// Data served from committed CSV snapshots under public/yelolgold/data/*.csv.
// An era only appears in the Music grid if its name is a key in
// ALBUM_RELEASE_DATES; dates are unknown here since they weren't re-derived
// from this sheet, so every era is a placeholder until filled in by hand.
export const yelolgoldConfig: ArtistConfig = {
  slug: 'yelolgold',
  // Off the landing grid/search — reachable via yegold's alt-tracker picker
  // or directly at /yelolgold/.
  hidden: true,
  hasGroupbuysTab: true,
  hasAlbumCopiesTab: true,
  SITE_NAME: 'YE (Lol)',
  SITE_DESCRIPTION: 'The Kanye West tracker, alternate "Lol" version',
  SITE_URL: 'https://unvaulted.cc/yelolgold/',
  OG_IMAGE_URL: 'https://i.ibb.co/LhXdRh7j/2026-03-23-T184041-712.png',
  STORAGE_PREFIX: 'yelolgold_',

  HARDCODED_SHEET_ID: '1wQ0WC0U9q10fLWpy9CO8YR128eE8msGXqtZI8_cNyTA',
  HARDCODED_SHEET_GID: '199908479',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1wQ0WC0U9q10fLWpy9CO8YR128eE8msGXqtZI8_cNyTA/export?format=csv&gid=689133373',

  alternateTrackers: [
    { slug: 'yegold', label: 'Official' },
    { slug: 'yzygold', label: 'Suzy' },
  ],

  accentColor: '#C9A224',
  artistLabel: 'Ye (Lol)',
  cardLetter: 'LOL',
  logoUrl: '/logos/yzygold.png',
  artistPhotoUrl: '/artists/kanye.jpg',
  navLogoUrl: '/yzygold/logo.png',

  getArtistName() {
    return 'Kanye West';
  },

  CUSTOM_IMAGES: {
    'Jesus Is Born': '/yegold/JesusIsBorn.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Before The College Dropout': '??/??/????',
    'The College Dropout': '??/??/????',
    'Late Registration': '??/??/????',
    'Graduation': '??/??/????',
    '808s & Heartbreak': '??/??/????',
    'Good Ass Job': '??/??/????',
    'My Beautiful Dark Twisted Fantasy': '??/??/????',
    'Watch The Throne': '??/??/????',
    'Cruel Summer': '??/??/????',
    'Thank God For Drugs': '??/??/????',
    'Yeezus': '??/??/????',
    'Cruel Winter [V1]': '??/??/????',
    'Yeezus 2': '??/??/????',
    'So Help Me God': '??/??/????',
    'SWISH': '??/??/????',
    'The Life Of Pablo': '??/??/????',
    'Cruel Winter [V2]': '??/??/????',
    'Turbo Grafx 16': '??/??/????',
    'LOVE EVERYONE': '??/??/????',
    'DAYTONA': '??/??/????',
    'ye': '??/??/????',
    'KIDS SEE GHOSTS': '??/??/????',
    'Good Ass Job (2018)': '??/??/????',
    'Yandhi [V1]': '??/??/????',
    'Yandhi [V2]': '??/??/????',
    'JESUS IS KING': '??/??/????',
    'God\'s Country': '??/??/????',
    'JESUS IS KING: The Dr. Dre Version': '??/??/????',
    'DONDA [V1]': '??/??/????',
    'Donda [V2]': '??/??/????',
    'Donda [V3]': '??/??/????',
    'Jesus Is Born': '??/??/????',
    'DONDA 2 [V1]': '??/??/????',
    'WAR': '??/??/????',
    'YEBU': '??/??/????',
    'Bad Bitch Playbook': '??/??/????',
    'VULTURES 1': '??/??/????',
    'VULTURES 2': '??/??/????',
    'VULTURES 3': '??/??/????',
    'BULLY [V1]': '??/??/????',
    'CUCK': '??/??/????',
    'DONDA 2 [V2]': '??/??/????',
    'IN A PERFECT WORLD': '??/??/????',
    'BULLY [V2]': '??/??/????',
    'Ongoing': '??/??/????'
  },

  // Jesus Is Born is the Sunday Service Choir's own standalone album (merged
  // in from the sheet's SSC tab, see EXTRA_UNRELEASED_GIDS in _sheets.ts) —
  // other SSC recordings are filed under whichever studio era they're from
  // instead, tagged "(Sunday Service Choir)" in the song name.
  HIDDEN_ALBUMS: ['Jesus Is Born'],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},

  ALBUM_ORDER: [
    'Before The College Dropout',
    'The College Dropout',
    'Late Registration',
    'Graduation',
    '808s & Heartbreak',
    'Good Ass Job',
    'My Beautiful Dark Twisted Fantasy',
    'Watch The Throne',
    'Cruel Summer',
    'Thank God For Drugs',
    'Yeezus',
    'Cruel Winter [V1]',
    'Yeezus 2',
    'So Help Me God',
    'SWISH',
    'The Life Of Pablo',
    'Cruel Winter [V2]',
    'Turbo Grafx 16',
    'LOVE EVERYONE',
    'DAYTONA',
    'ye',
    'KIDS SEE GHOSTS',
    'Good Ass Job (2018)',
    'Yandhi [V1]',
    'Yandhi [V2]',
    'JESUS IS KING',
    'God\'s Country',
    'JESUS IS KING: The Dr. Dre Version',
    'DONDA [V1]',
    'Donda [V2]',
    'Donda [V3]',
    'Jesus Is Born',
    'DONDA 2 [V1]',
    'WAR',
    'YEBU',
    'Bad Bitch Playbook',
    'VULTURES 1',
    'VULTURES 2',
    'VULTURES 3',
    'BULLY [V1]',
    'CUCK',
    'DONDA 2 [V2]',
    'IN A PERFECT WORLD',
    'BULLY [V2]',
    'Ongoing'
  ],

  TAG_MAP: {
    '⭐': 'Best Of',
    '🏆': 'Grails',
    '🥇': 'Wanted',
    '🏅': 'Wanted',
    '✨': 'Special',
    '🗑️': 'Worst Of',
    '🗑': 'Worst Of',
    '🚮': 'Unwanted',
    '🤖': 'AI',
    '⁉️': 'Lost Media',
    '⁉': 'Lost Media',
    '❓': 'Unknown',
  },
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs that are not good enough to be in Best Of, but still deserves to be highlighted.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
  },
  ERA_THEMES: {},
  hasSubAlbumsTab: false,
};
